name: Add additional reviews

on:
 pull_request:
   types: [opened, synchronize]

jobs:
 add-reviews:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v2

     - name: Add additional reviews
       uses: actions/request-review@v2
       with:
         paths: "src/file1.py, src/file2.py"
         reviewers: "m1rl0k"
