on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      COVERAGE_DATA_PATH: /*
    steps:
      - uses: actions/checkout@v2

      - uses: arduino/cpp-test-action@v1
        
        with:
          coverage-data-path: ${{ env.COVERAGE_DATA_PATH }}
