on: [push]

jobs:

  build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module PSSecretScanner
            Get-Module PSSecretScanner -ListAvailable
          shell: pwsh
  windows_run:
    name: PSSecret
    runs-on: windows-latest
    steps:
      - name: Basic PowerShell commands 
 	env: 
          MY_NAME: John Smith   
        run: |
           find-secret ./
           write-output $env:MY_NAME
        shell: powershell   
